// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cancellieri.andre.ecommerc.Migrations.databasePMigrations
{
    [DbContext(typeof(databaseP))]
    partial class databasePModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Prodotti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });
#pragma warning restore 612, 618
        }
    }
}
